### ISSUE TITLE
Using Marko as the template engine or...

### ISSUE THREAD

**Issue by ghost** [jsdocs/jsdocs#21]
I was wondering if there is a specific reason for using Handlebars? I have been wanting to try Marko for a long time and this looks like a nice opportunity, what do you think @h2non? Or maybe go further and use Elm for all the front-end? 🤔  I haven't used any of those two yet so I don't know how that would work but looks interesting, though if Handlebars is the final choice is fine to me too.

**Comment by h2non** [comment]
We were using Handlebars simply because it fits better with the `jsdocumentation` library, but I don't like Handlebars either, so ideally we can use Jade/Pug. I don't have experience with Marko, but looks like a reasonable solution.

I like Elm, but I don't think we can take much benefits using it in this project, mostly because, at the end, we won't make a huge usage of reactive programming in the browser side. jsdocs site should be simple, beautiful and easy to browse. Logic in the client-side should be minimal.

I would prefer keeping it simple and also invite other developers to help, instead of building cool funny things with it that is hard to understand for most people.

**Comment by ghost** [comment]
Okay cool! I might switch to Pug then, which is the one I use the most so is faster to get started, I could take a deeper look into Marko some day, though. 
Thanks.
